In [1]:
import pandas as pd
import numpy as np

In [3]:
dt=pd.read_csv(r'/home/windows/Downloads/csv datasets/Data.csv')

In [4]:
dt

Country   Age   Salary Purchase
0   France  44.0  72000.0       No
1    Spain  27.0  48000.0      Yes
2  Germany  30.0  54000.0       No
3    Spain  38.0  61000.0       No
4  Germany  40.0      NaN      Yes
5   France  35.0  58000.0      Yes
6    Spain   NaN  52000.0       No
7   France  48.0  79000.0      Yes
8  Germany  50.0  83000.0       No
9   France  37.0  67000.0      Yes

In [10]:
x=dt[['Country','Age','Salary']].values

In [11]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [12]:
y=dt[['Purchase']].values

In [13]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [14]:
 from sklearn.impute import SimpleImputer

In [15]:
impute=SimpleImputer(missing_values=np.nan,strategy='mean')

In [20]:
imputer=impute.fit(x[:,1:3])

In [21]:
x[:,1:3]=imputer.transform(x[:,1:3])

In [22]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [23]:
 from sklearn.preprocessing import LabelEncoder

In [24]:
label_encoder_x=LabelEncoder()

In [25]:
x[:,0]=label_encoder_x.fit_transform(x[:,0])

In [26]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [27]:
label_encoder_y=LabelEncoder()

In [48]:
y=label_encoder_y.fit_transform(y)

In [49]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [50]:
 from sklearn.model_selection import train_test_split

In [51]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [52]:
x_train

array([[1, 40.0, 63777.77777777778],
       [0, 37.0, 67000.0],
       [2, 27.0, 48000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [2, 38.0, 61000.0],
       [0, 44.0, 72000.0],
       [0, 35.0, 58000.0]], dtype=object)

In [53]:
x_test

array([[1, 30.0, 54000.0],
       [1, 50.0, 83000.0]], dtype=object)

In [54]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [55]:
y_test

array([0, 0])

In [56]:
from sklearn.preprocessing import StandardScaler

In [57]:
sc_x=StandardScaler()

In [58]:
x_train=sc_x.fit_transform(x_train)

In [59]:
x_test=sc_x.transform(x_test)

In [60]:
x_train

array([[ 0.13483997,  0.26306757,  0.12381479],
       [-0.94387981, -0.25350148,  0.46175632],
       [ 1.21355975, -1.97539832, -1.53093341],
       [ 1.21355975,  0.05261351, -1.11141978],
       [-0.94387981,  1.64058505,  1.7202972 ],
       [ 1.21355975, -0.0813118 , -0.16751412],
       [-0.94387981,  0.95182631,  0.98614835],
       [-0.94387981, -0.59788085, -0.48214934]])

In [61]:
x_test

array([[ 0.13483997, -1.45882927, -0.90166297],
       [ 0.13483997,  1.98496442,  2.13981082]])